const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Arr,
		C3.Plugins.Sprite,
		C3.Behaviors.Fade,
		C3.Plugins.Text,
		C3.Plugins.Mouse,
		C3.Plugins.Audio,
		C3.Plugins.BinaryData,
		C3.Plugins.AJAX,
		C3.Plugins.skymen_Shell,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.skymen_Shell.Cnds.CompareInstanceVar,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.Mouse.Acts.SetCursor,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Acts.SetLayerOpacity,
		C3.Plugins.Sprite.Exps.Opacity,
		C3.Plugins.Text.Acts.SetOpacity,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.AJAX.Acts.RequestFile,
		C3.Behaviors.Fade.Cnds.OnFadeOutEnd,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.System.Exps.random,
		C3.Behaviors.Fade.Cnds.OnFadeInEnd,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Sprite.Acts.SetEffectEnabled,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Mouse.Exps.X,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.Arr.Acts.JSONLoad,
		C3.Plugins.AJAX.Exps.LastData,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.Sprite.Acts.SetOpacity
	];
};
self.C3_JsPropNameTable = [
	{BookPages: 0},
	{Fade: 0},
	{bookSprite: 0},
	{in: 0},
	{out: 0},
	{outtotitle: 0},
	{pageBackground: 0},
	{pageNext: 0},
	{pageList: 0},
	{pageText: 0},
	{pageText2: 0},
	{Mouse: 0},
	{Audio: 0},
	{BinaryData: 0},
	{AJAX: 0},
	{madeby: 0},
	{cap: 0},
	{listBook: 0},
	{id: 0},
	{interactable: 0},
	{page: 0},
	{chapter: 0},
	{ontransition: 0},
	{onSumary: 0}
];

self.InstanceType = {
	BookPages: class extends self.IArrayInstance {},
	bookSprite: class extends self.ISpriteInstance {},
	pageBackground: class extends self.ISpriteInstance {},
	pageNext: class extends self.ISpriteInstance {},
	pageList: class extends self.ITextInstance {},
	pageText: class extends self.ITextInstance {},
	pageText2: class extends self.ITextInstance {},
	Mouse: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	BinaryData: class extends self.IBinaryDataInstance {},
	AJAX: class extends self.IInstance {},
	madeby: class extends self.ITextInstance {},
	listBook: class extends self.ITextInstance {},
	interactable: class extends self.IWorldInstance {}
}